services:
    - type: worker
      name: ig-report-bot
      env: python
      plan: starter # use "starter" (paid) or "free" if allowed for your account
      autoDeploy: true
      buildCommand: pip install -r requirements.txt
      startCommand: python -m src.main

      # persistent storage (singular: "disk")
      disk:
          name: bot-db
          mountPath: /var/data
          sizeGB: 1

      envVars:
          - key: TELEGRAM_BOT_TOKEN
            sync: false # set in dashboard on first deploy
          - key: OPENAI_API_KEY
            sync: false # set in dashboard on first deploy
          - key: OPENAI_MODEL
            value: gpt-4o-mini
          - key: TIMEZONE
            value: Africa/Lagos
          - key: OCR_MODE
            value: openai
          - key: BOSS_CHAT_ID
            value: "-1002685860937" # wrap negatives in quotes
          - key: BOSS_THREAD_ID
            value: "9" # omit if you don’t use topics
          - key: FORCE_ENV_DESTINATION
            value: "1"
          - key: BOT_DB_PATH
            value: /var/data/bot.db
